Διάγραμμα Ακολουθίας
graphXDoses/Cinematrix pull request #101
Opened 2024-05-21 21:12 UTC by NAmax11

2024-05-21 21:46 UTC, graphXDoses requested changes
@NAmax11 το συμβολο του `Actor` δεν μου φαινεται σωστο. Περα απο το οτι εχεις αυτο `<< user >>\nActor` που δεν ειναι σωστο - γιατι ανεφερωμαστε ως χρηστη αρα απλα `Actor`- υπαρχει και αυτη η γραμμη σαν απαγορευτικο που δεν ειναι αυτο που θελουμε. Κανε συντομα τις αλλαγες και ανεβασε παλι. Ολα τα αλλα φαινονται ΟΚ

2024-05-21 21:56 UTC, Phoebus requested changes
Το διάγραμμα είναι λανθασμένο. Πρέπει να ξαναδιαβάσεις το [Use Case #6](https://docs.google.com/document/d/1pSBpAiJcKJQPN3fs5E3JTCixYXaErYt6hzxCn2PlW-4/edit).
Δε χρειάζεται να καλέσεις κάποια συνάρτηση getProjections() αφού είναι ήδη στην οθόνη τα projections. Πρέπει μόλις επιλέξει ένα projection ο χρήστης, αυτό να αποθηκευτεί προσωρινά.

2024-05-21 22:35 UTC, NAmax11 reviewed
![SelectMovieProjection](https://github.com/graphXDoses/Cinematrix/assets/166210955/95f698d5-522e-4938-a576-180504a8257e)

2024-05-21 22:35 UTC, NAmax11 commented
Αυτό είναι σωστό πιστεύω

2024-05-21 22:36 UTC, NAmax11 commented
αφού ο χρηστης βλεπει τις προβολες απτη "σελιδα" και επιλέγει αποθηκεύοντας

2024-05-22 14:21 UTC, Phoebus requested changes
Ο @StudVl πρότεινε να μη δημιουργήτε αντικείμενο τύπου Ticket μέχρι να κάνει confirmation ο χρήστης και κατανοώ τους λόγους για τους οποίους κάτι τέτοιο μπορεί να μας σώσει χρόνο. Παρόλα αυτά αυτές οι προσωρινές πληροφορίες που θα πρέπει κάπου να αποθηκευτούν πριν γίνει confirmation (όπως η θέση, ο τρόπος πληρωμής, ονοματεπώνυμο κτλ.) που θα αποθηκεύονται;;; Θα πρότεινα να δημιουργήτε lifeline με ένα Ticket entity ή κάποια ειδική κλάσση τύπου Temporary Ticket όπου και εκεί θα αποθηκεύονται τα στοιχεία. 
Θα ήθελα και την άποψη σας @graphXDoses @StudVl

2024-05-26 18:11 UTC, graphXDoses commented
@Phoebus ναι λογικο ειναι να δημιουργειται entitty `Ticket`. Το αν τελικα θα αποθηκευτει στη βαση θα κρινεται απο τις ενεργειες του χρηστη. Αρα αντιλαμβανεστε `ALT` με παρομοια δομη με το παραδειγμα εδω:
![2  Διάγραμμα Ακολουθίας Συστήματος](https://github.com/graphXDoses/Cinematrix/assets/22478681/ad7f3035-e1a9-43a4-9aee-2d622c19656f)
Και τη χρηση των αντιστοιχων **sd** UC##

2024-06-01 19:27 UTC, closed without merging